In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [2]:
data=pd.read_csv(r"data\car_purchase_dataset.csv")

In [3]:
data.head()

         Name  Age  Annual_Income Purchase_Car
0   Person_10   30         601896          Yes
1   Person_43   21         578480          Yes
2   Person_34   40         898376          Yes
3  Person_312   22         354162           No
4  Person_273   29         377738           No

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           390 non-null    str
 1   Age            390 non-null    int64
 2   Annual_Income  390 non-null    int64
 3   Purchase_Car   390 non-null    str
dtypes: int64(2), str(2)
memory usage: 17.0 KB

In [5]:
data.isna().sum()

Name             0
Age              0
Annual_Income    0
Purchase_Car     0
dtype: int64

In [6]:
data.duplicated().sum()

np.int64(0)

In [7]:
data.describe()

              Age  Annual_Income
count  390.000000   3.900000e+02
mean    37.161538   5.866986e+05
std     11.781300   3.707512e+05
min     20.000000   2.028690e+05
25%     27.000000   3.144638e+05
50%     36.000000   3.881610e+05
75%     47.000000   8.580555e+05
max     59.000000   1.497286e+06

In [8]:
data.to_csv(r"data\clean.csv")